[package]
name = "solang"
version = "0.1.0"
authors = ["Tanel Kriik <tanel.kriik+github@gmail.com>"]

[dependencies]
clap = { version = "2.32.0", features = ["yaml"] }
im = "12.1.0"
rustyline = "2.0.1"
time = "0.1.40"
unicode-segmentation = "1.1.0"

[dev-dependencies]
pretty_assertions = "0.5.1"
